language: python
python:
  - "3.6"
install:
  - pip install http://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
  - pip install torchvision pytest pytest-cov coveralls
  - pip install -e .
script:
  - pytest tests --cov=pytorch_refinenet
after_success:
  - coveralls
